<?php

namespace GlobalPayments\Api\Entities;

use GlobalPayments\Api\Entities\Enums\FundsStatus;
use GlobalPayments\Api\Entities\Enums\PaymentMethodName;
use GlobalPayments\Api\Entities\Enums\PaymentMethodType;
use GlobalPayments\Api\Entities\Enums\TransactionStatus;

class FundsAccountDetails
{
    /**
     * A unique identifier generated by Global Payments to identify a transfer
     * @var string
     */
    public $id;
    /**
     * Indicates where a Transfer is in its lifecycle.
     *
     * @var FundsStatus
     */
    public $status;

    /**
     * Global Payments time indicating when the object was created in ISO-8601 format.
     * @var string
     */
    public $timeCreated;

    public ?string $timeLastUpdated;

    /**
     * This is the amount being transferred.
     * @var string;
     */
    public $amount;

    public ?string $reference;
    public ?string $description;
    public ?string $currency;
    /** @var PaymentMethodType|null  */
    public ?string $paymentMethodType;
    /** @var PaymentMethodName|null  */
    public ?string $paymentMethodName;
    public ?UserAccount $account;
}