<?php

namespace GlobalPayments\Api\Entities;

use GlobalPayments\Api\Entities\Enums\TransactionStatus;

class TransferFundsAccountDetails
{
    /**
     * A unique identifier generated by Global Payments to identify a transfer
     * @var string
     */
    public $id;
    /**
     * Indicates where a Transfer is in its lifecycle.
     *
     * @var TransactionStatus
     */
    public $status;

    /**
     * Global Payments time indicating when the object was created in ISO-8601 format.
     * @var string
     */
    public $timeCreated;

    /**
     * This is the amount being transferred.
     * @var string;
     */
    public $amount;

    /**
     * Split reference number
     * @var string
     */
    public $reference;

    /**
     * The description of the split.
     * @var string
     */
    public $description;
}