<?php

namespace GlobalPayments\Api\Entities\Enums;

use GlobalPayments\Api\Entities\Enum;

class BankPaymentStatus extends Enum
{
    const PAYMENT_INITIATED = 'PAYMENT_INITIATED';
    const REQUEST_CONSUMER_CONSENT = 'REQUEST_CONSUMER_CONSENT';
    const PROCESSING = 'PROCESSING';
    const UNKNOWN = 'UNKNOWN';
    const SUCCESS = 'SUCCESS';
    const INVALID_STATUS = 'INVALID_STATUS';
    const FAILURE_INSUFFICIENT_FUNDS = 'FAILURE_INSUFFICIENT_FUNDS';
    const FAILURE_INVALID_CURRENCY = 'FAILURE_INVALID_CURRENCY';
    const FAILURE_GENERIC = 'FAILURE_GENERIC';
    const FAILURE_PERMISSION_DENIED = 'FAILURE_PERMISSION_DENIED';
    const FAILURE_CANCELED = 'FAILURE_CANCELED';
    const FAILURE_QUOTE_EXPIRED = 'FAILURE_QUOTE_EXPIRED';
    const FAILURE_INVALID_AMOUNT = 'FAILURE_INVALID_AMOUNT';
    const FAILURE_INVALID_QUOTE = 'FAILURE_INVALID_QUOTE';
    const FAILURE_EXPIRED = 'FAILURE_EXPIRED';
    const PENDING_EXTERNAL_AUTHORIZATION = 'PENDING_EXTERNAL_AUTHORIZATION';
    const FAILURE_DECLINED = 'FAILURE_DECLINED';
    const STATUS_NOT_AVAILABLE = 'STATUS_NOT_AVAILABLE';
    const PAYMENT_NOT_COMPLETED = 'PAYMENT_NOT_COMPLETED';
}