<?php

namespace GlobalPayments\Api\Entities\Enums;

use GlobalPayments\Api\Entities\Enum;

class ChallengeRequestIndicator extends Enum
{
    const NO_PREFERENCE = "NO_PREFERENCE";
    const NO_CHALLENGE_REQUESTED = "NO_CHALLENGE_REQUESTED";
    const CHALLENGE_PREFERRED = "CHALLENGE_PREFERRED";
    const CHALLENGE_MANDATED = "CHALLENGE_MANDATED";
    const NO_CHALLENGE_REQUESTED_TRANSACTION_RISK_ANALYSIS_PERFORMED = "NO_CHALLENGE_REQUESTED_TRANSACTION_RISK_ANALYSIS_PERFORMED";
    const NO_CHALLENGE_REQUESTED_DATA_SHARE_ONLY = "NO_CHALLENGE_REQUESTED_DATA_SHARE_ONLY";
    const NO_CHALLENGE_REQUESTED_SCA_ALREADY_PERFORMED = "NO_CHALLENGE_REQUESTED_SCA_ALREADY_PERFORMED";
    const NO_CHALLENGE_REQUESTED_WHITELIST = "NO_CHALLENGE_REQUESTED_WHITELIST";
    const CHALLENGE_REQUESTED_PROMPT_FOR_WHITELIST = "CHALLENGE_REQUESTED_PROMPT_FOR_WHITELIST";
}
