<?php


namespace GlobalPayments\Api\Entities\Enums;


class IsoCountries
{
    public static $allCountries = [
        ["name" => "Afghanistan", "numeric" => "004", "alpha2" => "AF", "alpha3" => "AFG", "phoneCode" => ["93"]],
        ["name" => "Åland Islands", "numeric" => "248", "alpha2" => "AX", "alpha3" => "ALA", "phoneCode" => ["358"]],
        ["name" => "Albania", "numeric" => "008", "alpha2" => "AL", "alpha3" => "ALB", "phoneCode" => ["355"]],
        ["name" => "Algeria", "numeric" => "012", "alpha2" => "DZ", "alpha3" => "DZA", "phoneCode" => ["213"]],
        ["name" => "American Samoa", "numeric" => "016", "alpha2" => "AS", "alpha3" => "ASM", "phoneCode" => ["1-684"]],
        ["name" => "Andorra", "numeric" => "020", "alpha2" => "AD", "alpha3" => "AND", "phoneCode" => ["376"]],
        ["name" => "Angola", "numeric" => "024", "alpha2" => "AO", "alpha3" => "AGO", "phoneCode" => ["244"]],
        ["name" => "Anguilla", "numeric" => "660", "alpha2" => "AI", "alpha3" => "AIA", "phoneCode" => ["1-264"]],
        ["name" => "Antarctica", "numeric" => "010", "alpha2" => "AQ", "alpha3" => "ATA", "phoneCode" => ["672"]],
        ["name" => "Antigua and Barbuda", "numeric" => "028", "alpha2" => "AG", "alpha3" => "ATG", "phoneCode" => ["1-268"]],
        ["name" => "Argentina", "numeric" => "032", "alpha2" => "AR", "alpha3" => "ARG", "phoneCode" => ["54"]],
        ["name" => "Armenia", "numeric" => "051", "alpha2" => "AM", "alpha3" => "ARM", "phoneCode" => ["374"]],
        ["name" => "Aruba", "numeric" => "533", "alpha2" => "AW", "alpha3" => "ABW", "phoneCode" => ["297"]],
        ["name" => "Australia", "numeric" => "036", "alpha2" => "AU", "alpha3" => "AUS", "phoneCode" => ["61"]],
        ["name" => "Austria", "numeric" => "040", "alpha2" => "AT", "alpha3" => "AUT", "phoneCode" => ["43"]],
        ["name" => "Azerbaijan", "numeric" => "031", "alpha2" => "AZ", "alpha3" => "AZE", "phoneCode" => ["994"]],
        ["name" => "Bahamas", "numeric" => "044", "alpha2" => "BS", "alpha3" => "BHS", "phoneCode" => ["1-242"]],
        ["name" => "Bahrain", "numeric" => "048", "alpha2" => "BH", "alpha3" => "BHR", "phoneCode" => ["973"]],
        ["name" => "Bangladesh", "numeric" => "050", "alpha2" => "BD", "alpha3" => "BGD", "phoneCode" => ["880"]],
        ["name" => "Barbados", "numeric" => "052", "alpha2" => "BB", "alpha3" => "BRB", "phoneCode" => ["1-246"]],
        ["name" => "Belarus", "numeric" => "112", "alpha2" => "BY", "alpha3" => "BLR", "phoneCode" => ["375"]],
        ["name" => "Belgium", "numeric" => "056", "alpha2" => "BE", "alpha3" => "BEL", "phoneCode" => ["32"]],
        ["name" => "Belize", "numeric" => "084", "alpha2" => "BZ", "alpha3" => "BLZ", "phoneCode" => ["501"]],
        ["name" => "Benin", "numeric" => "204", "alpha2" => "BJ", "alpha3" => "BEN", "phoneCode" => ["229"]],
        ["name" => "Bermuda", "numeric" => "060", "alpha2" => "BM", "alpha3" => "BMU", "phoneCode" => ["1-441"]],
        ["name" => "Bhutan", "numeric" => "064", "alpha2" => "BT", "alpha3" => "BTN", "phoneCode" => ["975"]],
        ["name" => "Bolivia, Plurinational State of", "numeric" => "068", "alpha2" => "BO", "alpha3" => "BOL", "phoneCode" => ["591"]],
        ["name" => "Bonaire, Sint Eustatius and Saba", "numeric" => "535", "alpha2" => "BQ", "alpha3" => "BES", "phoneCode" => ["599"]],
        ["name" => "Bosnia and Herzegovina", "numeric" => "070", "alpha2" => "BA", "alpha3" => "BIH", "phoneCode" => ["387"]],
        ["name" => "Botswana", "numeric" => "072", "alpha2" => "BW", "alpha3" => "BWA", "phoneCode" => ["267"]],
        ["name" => "Bouvet Island", "numeric" => "074", "alpha2" => "BV", "alpha3" => "BVT", "phoneCode" => ["55"]],
        ["name" => "Brazil", "numeric" => "076", "alpha2" => "BR", "alpha3" => "BRA", "phoneCode" => ["55"]],
        ["name" => "British Indian Ocean Territory", "numeric" => "086", "alpha2" => "IO", "alpha3" => "IOT", "phoneCode" => ["246"]],
        ["name" => "Brunei Darussalam", "numeric" => "096", "alpha2" => "BN", "alpha3" => "BRN", "phoneCode" => ["673"]],
        ["name" => "Bulgaria", "numeric" => "100", "alpha2" => "BG", "alpha3" => "BGR", "phoneCode" => ["359"]],
        ["name" => "Burkina Faso", "numeric" => "854", "alpha2" => "BF", "alpha3" => "BFA", "phoneCode" => ["226"]],
        ["name" => "Burundi", "numeric" => "108", "alpha2" => "BI", "alpha3" => "BDI", "phoneCode" => ["257"]],
        ["name" => "Cambodia", "numeric" => "116", "alpha2" => "KH", "alpha3" => "KHM", "phoneCode" => ["855"]],
        ["name" => "Cameroon", "numeric" => "120", "alpha2" => "CM", "alpha3" => "CMR", "phoneCode" => ["237"]],
        ["name" => "Canada", "numeric" => "124", "alpha2" => "CA", "alpha3" => "CAN", "phoneCode" => ["1"]],
        ["name" => "Cabo Verde", "numeric" => "132", "alpha2" => "CV", "alpha3" => "CPV", "phoneCode" => ["238"]],
        ["name" => "Cayman Islands", "numeric" => "136", "alpha2" => "KY", "alpha3" => "CYM", "phoneCode" => ["1-345"]],
        ["name" => "Central African Republic", "numeric" => "140", "alpha2" => "CF", "alpha3" => "CAF", "phoneCode" => ["236"]],
        ["name" => "Chad", "numeric" => "148", "alpha2" => "TD", "alpha3" => "TCD", "phoneCode" => ["235"]],
        ["name" => "Chile", "numeric" => "152", "alpha2" => "CL", "alpha3" => "CHL", "phoneCode" => ["56"]],
        ["name" => "China", "numeric" => "156", "alpha2" => "CN", "alpha3" => "CHN", "phoneCode" => ["86"]],
        ["name" => "Christmas Island", "numeric" => "162", "alpha2" => "CX", "alpha3" => "CXR", "phoneCode" => ["61"]],
        ["name" => "Cocos (Keeling) Islands", "numeric" => "166", "alpha2" => "CC", "alpha3" => "CCK", "phoneCode" => ["61"]],
        ["name" => "Colombia", "numeric" => "170", "alpha2" => "CO", "alpha3" => "COL", "phoneCode" => ["57"]],
        ["name" => "Comoros", "numeric" => "174", "alpha2" => "KM", "alpha3" => "COM", "phoneCode" => ["269"]],
        ["name" => "Congo", "numeric" => "178", "alpha2" => "CG", "alpha3" => "COG", "phoneCode" => ["242"]],
        ["name" => "Congo, the Democratic Republic of the", "numeric" => "180", "alpha2" => "CD", "alpha3" => "COD", "phoneCode" => ["243"]],
        ["name" => "Cook Islands", "numeric" => "184", "alpha2" => "CK", "alpha3" => "COK", "phoneCode" => ["682"]],
        ["name" => "Costa Rica", "numeric" => "188", "alpha2" => "CR", "alpha3" => "CRI", "phoneCode" => ["506"]],
        ["name" => "Côte d'Ivoire", "numeric" => "384", "alpha2" => "CI", "alpha3" => "CIV", "phoneCode" => ["225"]],
        ["name" => "Croatia", "numeric" => "191", "alpha2" => "HR", "alpha3" => "HRV", "phoneCode" => ["385"]],
        ["name" => "Cuba", "numeric" => "192", "alpha2" => "CU", "alpha3" => "CUB", "phoneCode" => ["53"]],
        ["name" => "Curaçao", "numeric" => "531", "alpha2" => "CW", "alpha3" => "CUW", "phoneCode" => ["599"]],
        ["name" => "Cyprus", "numeric" => "196", "alpha2" => "CY", "alpha3" => "CYP", "phoneCode" => ["357"]],
        ["name" => "Czech Republic", "numeric" => "203", "alpha2" => "CZ", "alpha3" => "CZE", "phoneCode" => ["420"]],
        ["name" => "Denmark", "numeric" => "208", "alpha2" => "DK", "alpha3" => "DNK", "phoneCode" => ["45"]],
        ["name" => "Djibouti", "numeric" => "262", "alpha2" => "DJ", "alpha3" => "DJI", "phoneCode" => ["253"]],
        ["name" => "Dominica", "numeric" => "212", "alpha2" => "DM", "alpha3" => "DMA", "phoneCode" => ["1-767"]],
        ["name" => "Dominican Republic", "numeric" => "214", "alpha2" => "DO", "alpha3" => "DOM", "phoneCode" => ["1-809", "1-829", "1-849"]],
        ["name" => "Ecuador", "numeric" => "218", "alpha2" => "EC", "alpha3" => "ECU", "phoneCode" => ["593"]],
        ["name" => "Egypt", "numeric" => "818", "alpha2" => "EG", "alpha3" => "EGY", "phoneCode" => ["20"]],
        ["name" => "El Salvador", "numeric" => "222", "alpha2" => "SV", "alpha3" => "SLV", "phoneCode" => ["503"]],
        ["name" => "Equatorial Guinea", "numeric" => "226", "alpha2" => "GQ", "alpha3" => "GNQ", "phoneCode" => ["240"]],
        ["name" => "Eritrea", "numeric" => "232", "alpha2" => "ER", "alpha3" => "ERI", "phoneCode" => ["291"]],
        ["name" => "Estonia", "numeric" => "233", "alpha2" => "EE", "alpha3" => "EST", "phoneCode" => ["372"]],
        ["name" => "Ethiopia", "numeric" => "231", "alpha2" => "ET", "alpha3" => "ETH", "phoneCode" => ["251"]],
        ["name" => "Falkland Islands (Malvinas)", "numeric" => "238", "alpha2" => "FK", "alpha3" => "FLK", "phoneCode" => ["500"]],
        ["name" => "Faroe Islands", "numeric" => "234", "alpha2" => "FO", "alpha3" => "FRO", "phoneCode" => ["298"]],
        ["name" => "Fiji", "numeric" => "242", "alpha2" => "FJ", "alpha3" => "FJI", "phoneCode" => ["679"]],
        ["name" => "Finland", "numeric" => "246", "alpha2" => "FI", "alpha3" => "FIN", "phoneCode" => ["358"]],
        ["name" => "France", "numeric" => "250", "alpha2" => "FR", "alpha3" => "FRA", "phoneCode" => ["33"]],
        ["name" => "French Guiana", "numeric" => "254", "alpha2" => "GF", "alpha3" => "GUF", "phoneCode" => ["594"]],
        ["name" => "French Polynesia", "numeric" => "258", "alpha2" => "PF", "alpha3" => "PYF", "phoneCode" => ["689"]],
        ["name" => "French Southern Territories", "numeric" => "260", "alpha2" => "TF", "alpha3" => "ATF", "phoneCode" => ["262"]],
        ["name" => "Gabon", "numeric" => "266", "alpha2" => "GA", "alpha3" => "GAB", "phoneCode" => ["241"]],
        ["name" => "Gambia", "numeric" => "270", "alpha2" => "GM", "alpha3" => "GMB", "phoneCode" => ["220"]],
        ["name" => "Georgia", "numeric" => "268", "alpha2" => "GE", "alpha3" => "GEO", "phoneCode" => ["995"]],
        ["name" => "Germany", "numeric" => "276", "alpha2" => "DE", "alpha3" => "DEU", "phoneCode" => ["49"]],
        ["name" => "Ghana", "numeric" => "288", "alpha2" => "GH", "alpha3" => "GHA", "phoneCode" => ["233"]],
        ["name" => "Gibraltar", "numeric" => "292", "alpha2" => "GI", "alpha3" => "GIB", "phoneCode" => ["350"]],
        ["name" => "Greece", "numeric" => "300", "alpha2" => "GR", "alpha3" => "GRC", "phoneCode" => ["30"]],
        ["name" => "Greenland", "numeric" => "304", "alpha2" => "GL", "alpha3" => "GRL", "phoneCode" => ["299"]],
        ["name" => "Grenada", "numeric" => "308", "alpha2" => "GD", "alpha3" => "GRD", "phoneCode" => ["1-473"]],
        ["name" => "Guadeloupe", "numeric" => "312", "alpha2" => "GP", "alpha3" => "GLP", "phoneCode" => ["590"]],
        ["name" => "Guam", "numeric" => "316", "alpha2" => "GU", "alpha3" => "GUM", "phoneCode" => ["1-671"]],
        ["name" => "Guatemala", "numeric" => "320", "alpha2" => "GT", "alpha3" => "GTM", "phoneCode" => ["502"]],
        ["name" => "Guernsey", "numeric" => "831", "alpha2" => "GG", "alpha3" => "GGY", "phoneCode" => ["44-1481"]],
        ["name" => "Guinea", "numeric" => "324", "alpha2" => "GN", "alpha3" => "GIN", "phoneCode" => ["224"]],
        ["name" => "Guinea-Bissau", "numeric" => "624", "alpha2" => "GW", "alpha3" => "GNB", "phoneCode" => ["245"]],
        ["name" => "Guyana", "numeric" => "328", "alpha2" => "GY", "alpha3" => "GUY", "phoneCode" => ["592"]],
        ["name" => "Haiti", "numeric" => "332", "alpha2" => "HT", "alpha3" => "HTI", "phoneCode" => ["509"]],
        ["name" => "Heard Island and McDonald Islands", "numeric" => "334", "alpha2" => "HM", "alpha3" => "HMD", "phoneCode" => ["672"]],
        ["name" => "Holy See (Vatican City State)", "numeric" => "336", "alpha2" => "VA", "alpha3" => "VAT", "phoneCode" => ["379"]],
        ["name" => "Honduras", "numeric" => "340", "alpha2" => "HN", "alpha3" => "HND", "phoneCode" => ["504"]],
        ["name" => "Hong Kong", "numeric" => "344", "alpha2" => "HK", "alpha3" => "HKG", "phoneCode" => ["852"]],
        ["name" => "Hungary", "numeric" => "348", "alpha2" => "HU", "alpha3" => "HUN", "phoneCode" => ["36"]],
        ["name" => "Iceland", "numeric" => "352", "alpha2" => "IS", "alpha3" => "ISL", "phoneCode" => ["354"]],
        ["name" => "India", "numeric" => "356", "alpha2" => "IN", "alpha3" => "IND", "phoneCode" => ["91"]],
        ["name" => "Indonesia", "numeric" => "360", "alpha2" => "ID", "alpha3" => "IDN", "phoneCode" => ["62"]],
        ["name" => "Iran, Islamic Republic of", "numeric" => "364", "alpha2" => "IR", "alpha3" => "IRN", "phoneCode" => ["98"]],
        ["name" => "Iraq", "numeric" => "368", "alpha2" => "IQ", "alpha3" => "IRQ", "phoneCode" => ["964"]],
        ["name" => "Ireland", "numeric" => "372", "alpha2" => "IE", "alpha3" => "IRL", "phoneCode" => ["353"]],
        ["name" => "Isle of Man", "numeric" => "833", "alpha2" => "IM", "alpha3" => "IMN", "phoneCode" => ["44-1624"]],
        ["name" => "Israel", "numeric" => "376", "alpha2" => "IL", "alpha3" => "ISR", "phoneCode" => ["972"]],
        ["name" => "Italy", "numeric" => "380", "alpha2" => "IT", "alpha3" => "ITA", "phoneCode" => ["39"]],
        ["name" => "Jamaica", "numeric" => "388", "alpha2" => "JM", "alpha3" => "JAM", "phoneCode" => ["1-876"]],
        ["name" => "Japan", "numeric" => "392", "alpha2" => "JP", "alpha3" => "JPN", "phoneCode" => ["81"]],
        ["name" => "Jersey", "numeric" => "832", "alpha2" => "JE", "alpha3" => "JEY", "phoneCode" => ["44-1534"]],
        ["name" => "Jordan", "numeric" => "400", "alpha2" => "JO", "alpha3" => "JOR", "phoneCode" => ["962"]],
        ["name" => "Kazakhstan", "numeric" => "398", "alpha2" => "KZ", "alpha3" => "KAZ", "phoneCode" => ["7"]],
        ["name" => "Kenya", "numeric" => "404", "alpha2" => "KE", "alpha3" => "KEN", "phoneCode" => ["254"]],
        ["name" => "Kiribati", "numeric" => "296", "alpha2" => "KI", "alpha3" => "KIR", "phoneCode" => ["686"]],
        ["name" => "Korea, Democratic People's Republic of", "numeric" => "408", "alpha2" => "KP", "alpha3" => "PRK", "phoneCode" => ["850"]],
        ["name" => "Korea, Republic of", "numeric" => "410", "alpha2" => "KR", "alpha3" => "KOR", "phoneCode" => ["82"]],
        ["name" => "Kuwait", "numeric" => "414", "alpha2" => "KW", "alpha3" => "KWT", "phoneCode" => ["965"]],
        ["name" => "Kyrgyzstan", "numeric" => "417", "alpha2" => "KG", "alpha3" => "KGZ", "phoneCode" => ["996"]],
        ["name" => "Lao People's Democratic Republic", "numeric" => "418", "alpha2" => "LA", "alpha3" => "LAO", "phoneCode" => ["856"]],
        ["name" => "Latvia", "numeric" => "428", "alpha2" => "LV", "alpha3" => "LVA", "phoneCode" => ["371"]],
        ["name" => "Lebanon", "numeric" => "422", "alpha2" => "LB", "alpha3" => "LBN", "phoneCode" => ["961"]],
        ["name" => "Lesotho", "numeric" => "426", "alpha2" => "LS", "alpha3" => "LSO", "phoneCode" => ["266"]],
        ["name" => "Liberia", "numeric" => "430", "alpha2" => "LR", "alpha3" => "LBR", "phoneCode" => ["231"]],
        ["name" => "Libya", "numeric" => "434", "alpha2" => "LY", "alpha3" => "LBY", "phoneCode" => ["218"]],
        ["name" => "Liechtenstein", "numeric" => "438", "alpha2" => "LI", "alpha3" => "LIE", "phoneCode" => ["423"]],
        ["name" => "Lithuania", "numeric" => "440", "alpha2" => "LT", "alpha3" => "LTU", "phoneCode" => ["370"]],
        ["name" => "Luxembourg", "numeric" => "442", "alpha2" => "LU", "alpha3" => "LUX", "phoneCode" => ["352"]],
        ["name" => "Macao", "numeric" => "446", "alpha2" => "MO", "alpha3" => "MAC", "phoneCode" => ["853"]],
        ["name" => "Macedonia, the former Yugoslav Republic of", "numeric" => "807", "alpha2" => "MK", "alpha3" => "MKD", "phoneCode" => ["389"]],
        ["name" => "Madagascar", "numeric" => "450", "alpha2" => "MG", "alpha3" => "MDG", "phoneCode" => ["261"]],
        ["name" => "Malawi", "numeric" => "454", "alpha2" => "MW", "alpha3" => "MWI", "phoneCode" => ["265"]],
        ["name" => "Malaysia", "numeric" => "458", "alpha2" => "MY", "alpha3" => "MYS", "phoneCode" => ["60"]],
        ["name" => "Maldives", "numeric" => "462", "alpha2" => "MV", "alpha3" => "MDV", "phoneCode" => ["960"]],
        ["name" => "Mali", "numeric" => "466", "alpha2" => "ML", "alpha3" => "MLI", "phoneCode" => ["223"]],
        ["name" => "Malta", "numeric" => "470", "alpha2" => "MT", "alpha3" => "MLT", "phoneCode" => ["356"]],
        ["name" => "Marshall Islands", "numeric" => "584", "alpha2" => "MH", "alpha3" => "MHL", "phoneCode" => ["692"]],
        ["name" => "Martinique", "numeric" => "474", "alpha2" => "MQ", "alpha3" => "MTQ", "phoneCode" => ["596"]],
        ["name" => "Mauritania", "numeric" => "478", "alpha2" => "MR", "alpha3" => "MRT", "phoneCode" => ["222"]],
        ["name" => "Mauritius", "numeric" => "480", "alpha2" => "MU", "alpha3" => "MUS", "phoneCode" => ["230"]],
        ["name" => "Mayotte", "numeric" => "175", "alpha2" => "YT", "alpha3" => "MYT", "phoneCode" => ["262"]],
        ["name" => "Mexico", "numeric" => "484", "alpha2" => "MX", "alpha3" => "MEX", "phoneCode" => ["52"]],
        ["name" => "Micronesia, Federated States of", "numeric" => "583", "alpha2" => "FM", "alpha3" => "FSM", "phoneCode" => ["691"]],
        ["name" => "Moldova, Republic of", "numeric" => "498", "alpha2" => "MD", "alpha3" => "MDA", "phoneCode" => ["373"]],
        ["name" => "Monaco", "numeric" => "492", "alpha2" => "MC", "alpha3" => "MCO", "phoneCode" => ["377"]],
        ["name" => "Mongolia", "numeric" => "496", "alpha2" => "MN", "alpha3" => "MNG", "phoneCode" => ["976"]],
        ["name" => "Montenegro", "numeric" => "499", "alpha2" => "ME", "alpha3" => "MNE", "phoneCode" => ["382"]],
        ["name" => "Montserrat", "numeric" => "500", "alpha2" => "MS", "alpha3" => "MSR", "phoneCode" => ["1-664"]],
        ["name" => "Morocco", "numeric" => "504", "alpha2" => "MA", "alpha3" => "MAR", "phoneCode" => ["212"]],
        ["name" => "Mozambique", "numeric" => "508", "alpha2" => "MZ", "alpha3" => "MOZ", "phoneCode" => ["258"]],
        ["name" => "Myanmar", "numeric" => "104", "alpha2" => "MM", "alpha3" => "MMR", "phoneCode" => ["95"]],
        ["name" => "Namibia", "numeric" => "516", "alpha2" => "NA", "alpha3" => "NAM", "phoneCode" => ["264"]],
        ["name" => "Nauru", "numeric" => "520", "alpha2" => "NR", "alpha3" => "NRU", "phoneCode" => ["674"]],
        ["name" => "Nepal", "numeric" => "524", "alpha2" => "NP", "alpha3" => "NPL", "phoneCode" => ["977"]],
        ["name" => "Netherlands", "numeric" => "528", "alpha2" => "NL", "alpha3" => "NLD", "phoneCode" => ["31"]],
        ["name" => "Netherlands Antilles", "numeric" => "530", "alpha2" => "AN", "alpha3" => "ANT", "phoneCode" => ["599"]],
        ["name" => "New Caledonia", "numeric" => "540", "alpha2" => "NC", "alpha3" => "NCL", "phoneCode" => ["687"]],
        ["name" => "New Zealand", "numeric" => "554", "alpha2" => "NZ", "alpha3" => "NZL", "phoneCode" => ["64"]],
        ["name" => "Nicaragua", "numeric" => "558", "alpha2" => "NI", "alpha3" => "NIC", "phoneCode" => ["505"]],
        ["name" => "Niger", "numeric" => "562", "alpha2" => "NE", "alpha3" => "NER", "phoneCode" => ["227"]],
        ["name" => "Nigeria", "numeric" => "566", "alpha2" => "NG", "alpha3" => "NGA", "phoneCode" => ["234"]],
        ["name" => "Niue", "numeric" => "570", "alpha2" => "NU", "alpha3" => "NIU", "phoneCode" => ["683"]],
        ["name" => "Norfolk Island", "numeric" => "574", "alpha2" => "NF", "alpha3" => "NFK", "phoneCode" => ["672"]],
        ["name" => "Northern Mariana Islands", "numeric" => "580", "alpha2" => "MP", "alpha3" => "MNP", "phoneCode" => ["1-670"]],
        ["name" => "Norway", "numeric" => "578", "alpha2" => "NO", "alpha3" => "NOR", "phoneCode" => ["47"]],
        ["name" => "Oman", "numeric" => "512", "alpha2" => "OM", "alpha3" => "OMN", "phoneCode" => ["968"]],
        ["name" => "Pakistan", "numeric" => "586", "alpha2" => "PK", "alpha3" => "PAK", "phoneCode" => ["92"]],
        ["name" => "Palau", "numeric" => "585", "alpha2" => "PW", "alpha3" => "PLW", "phoneCode" => ["680"]],
        ["name" => "Palestine, State of", "numeric" => "275", "alpha2" => "PS", "alpha3" => "PSE", "phoneCode" => ["970"]],
        ["name" => "Panama", "numeric" => "591", "alpha2" => "PA", "alpha3" => "PAN", "phoneCode" => ["507"]],
        ["name" => "Papua New Guinea", "numeric" => "598", "alpha2" => "PG", "alpha3" => "PNG", "phoneCode" => ["675"]],
        ["name" => "Paraguay", "numeric" => "600", "alpha2" => "PY", "alpha3" => "PRY", "phoneCode" => ["595"]],
        ["name" => "Peru", "numeric" => "604", "alpha2" => "PE", "alpha3" => "PER", "phoneCode" => ["51"]],
        ["name" => "Philippines", "numeric" => "608", "alpha2" => "PH", "alpha3" => "PHL", "phoneCode" => ["63"]],
        ["name" => "Pitcairn", "numeric" => "612", "alpha2" => "PN", "alpha3" => "PCN", "phoneCode" => ["64"]],
        ["name" => "Poland", "numeric" => "616", "alpha2" => "PL", "alpha3" => "POL", "phoneCode" => ["48"]],
        ["name" => "Portugal", "numeric" => "620", "alpha2" => "PT", "alpha3" => "PRT", "phoneCode" => ["351"]],
        ["name" => "Puerto Rico", "numeric" => "630", "alpha2" => "PR", "alpha3" => "PRI", "phoneCode" => ["1-787", "1-939"]],
        ["name" => "Qatar", "numeric" => "634", "alpha2" => "QA", "alpha3" => "QAT", "phoneCode" => ["974"]],
        ["name" => "Réunion", "numeric" => "638", "alpha2" => "RE", "alpha3" => "REU", "phoneCode" => ["262"]],
        ["name" => "Romania", "numeric" => "642", "alpha2" => "RO", "alpha3" => "ROU", "phoneCode" => ["40"]],
        ["name" => "Russian Federation", "numeric" => "643", "alpha2" => "RU", "alpha3" => "RUS", "phoneCode" => ["7"]],
        ["name" => "Rwanda", "numeric" => "646", "alpha2" => "RW", "alpha3" => "RWA", "phoneCode" => ["250"]],
        ["name" => "Saint Barthélemy", "numeric" => "652", "alpha2" => "BL", "alpha3" => "BLM", "phoneCode" => ["590"]],
        ["name" => "Saint Helena, Ascension and Tristan da Cunha", "numeric" => "654", "alpha2" => "SH", "alpha3" => "SHN", "phoneCode" => ["290"]],
        ["name" => "Saint Kitts and Nevis", "numeric" => "659", "alpha2" => "KN", "alpha3" => "KNA", "phoneCode" => ["1-869"]],
        ["name" => "Saint Lucia", "numeric" => "662", "alpha2" => "LC", "alpha3" => "LCA", "phoneCode" => ["1-758"]],
        ["name" => "Saint Martin", "numeric" => "663", "alpha2" => "MF", "alpha3" => "MAF", "phoneCode" => ["590"]],
        ["name" => "Saint Pierre and Miquelon", "numeric" => "666", "alpha2" => "PM", "alpha3" => "SPM", "phoneCode" => ["508"]],
        ["name" => "Saint Vincent and the Grenadines", "numeric" => "670", "alpha2" => "VC", "alpha3" => "VCT", "phoneCode" => ["1-784"]],
        ["name" => "Samoa", "numeric" => "882", "alpha2" => "WS", "alpha3" => "WSM", "phoneCode" => ["685"]],
        ["name" => "San Marino", "numeric" => "674", "alpha2" => "SM", "alpha3" => "SMR", "phoneCode" => ["378"]],
        ["name" => "Sao Tome and Principe", "numeric" => "678", "alpha2" => "ST", "alpha3" => "STP", "phoneCode" => ["239"]],
        ["name" => "Saudi Arabia", "numeric" => "682", "alpha2" => "SA", "alpha3" => "SAU", "phoneCode" => ["966"]],
        ["name" => "Senegal", "numeric" => "686", "alpha2" => "SN", "alpha3" => "SEN", "phoneCode" => ["221"]],
        ["name" => "Serbia", "numeric" => "688", "alpha2" => "RS", "alpha3" => "SRB", "phoneCode" => ["381"]],
        ["name" => "Seychelles", "numeric" => "690", "alpha2" => "SC", "alpha3" => "SYC", "phoneCode" => ["248"]],
        ["name" => "Sierra Leone", "numeric" => "694", "alpha2" => "SL", "alpha3" => "SLE", "phoneCode" => ["232"]],
        ["name" => "Singapore", "numeric" => "702", "alpha2" => "SG", "alpha3" => "SGP", "phoneCode" => ["65"]],
        ["name" => "Sint Maarten (Dutch part)", "numeric" => "534", "alpha2" => "SX", "alpha3" => "SXM", "phoneCode" => ["1-721"]],
        ["name" => "Slovakia", "numeric" => "703", "alpha2" => "SK", "alpha3" => "SVK", "phoneCode" => ["421"]],
        ["name" => "Slovenia", "numeric" => "705", "alpha2" => "SI", "alpha3" => "SVN", "phoneCode" => ["386"]],
        ["name" => "Solomon Islands", "numeric" => "090", "alpha2" => "SB", "alpha3" => "SLB", "phoneCode" => ["677"]],
        ["name" => "Somalia", "numeric" => "706", "alpha2" => "SO", "alpha3" => "SOM", "phoneCode" => ["252"]],
        ["name" => "South Africa", "numeric" => "710", "alpha2" => "ZA", "alpha3" => "ZAF", "phoneCode" => ["27"]],
        ["name" => "South Georgia and the South Sandwich Islands", "numeric" => "239", "alpha2" => "GS", "alpha3" => "SGS", "phoneCode" => ["500"]],
        ["name" => "South Sudan", "numeric" => "728", "alpha2" => "SS", "alpha3" => "SSD", "phoneCode" => ["211"]],
        ["name" => "Spain", "numeric" => "724", "alpha2" => "ES", "alpha3" => "ESP", "phoneCode" => ["34"]],
        ["name" => "Sri Lanka", "numeric" => "144", "alpha2" => "LK", "alpha3" => "LKA", "phoneCode" => ["94"]],
        ["name" => "Sudan", "numeric" => "729", "alpha2" => "SD", "alpha3" => "SDN", "phoneCode" => ["249"]],
        ["name" => "Suriname", "numeric" => "740", "alpha2" => "SR", "alpha3" => "SUR", "phoneCode" => ["597"]],
        ["name" => "Svalbard and Jan Mayen", "numeric" => "744", "alpha2" => "SJ", "alpha3" => "SJM", "phoneCode" => ["47"]],
        ["name" => "Swaziland", "numeric" => "748", "alpha2" => "SZ", "alpha3" => "SWZ", "phoneCode" => ["268"]],
        ["name" => "Sweden", "numeric" => "752", "alpha2" => "SE", "alpha3" => "SWE", "phoneCode" => ["46"]],
        ["name" => "Switzerland", "numeric" => "756", "alpha2" => "CH", "alpha3" => "CHE", "phoneCode" => ["41"]],
        ["name" => "Syrian Arab Republic", "numeric" => "760", "alpha2" => "SY", "alpha3" => "SYR", "phoneCode" => ["963"]],
        ["name" => "Taiwan, Province of China", "numeric" => "158", "alpha2" => "TW", "alpha3" => "TWN", "phoneCode" => ["886"]],
        ["name" => "Tajikistan", "numeric" => "762", "alpha2" => "TJ", "alpha3" => "TJK", "phoneCode" => ["992"]],
        ["name" => "Tanzania, United Republic of", "numeric" => "834", "alpha2" => "TZ", "alpha3" => "TZA", "phoneCode" => ["255"]],
        ["name" => "Thailand", "numeric" => "764", "alpha2" => "TH", "alpha3" => "THA", "phoneCode" => ["66"]],
        ["name" => "Timor-Leste", "numeric" => "626", "alpha2" => "TL", "alpha3" => "TLS", "phoneCode" => ["670"]],
        ["name" => "Togo", "numeric" => "768", "alpha2" => "TG", "alpha3" => "TGO", "phoneCode" => ["228"]],
        ["name" => "Tokelau", "numeric" => "772", "alpha2" => "TK", "alpha3" => "TKL", "phoneCode" => ["690"]],
        ["name" => "Tonga", "numeric" => "776", "alpha2" => "TO", "alpha3" => "TON", "phoneCode" => ["676"]],
        ["name" => "Trinidad and Tobago", "numeric" => "780", "alpha2" => "TT", "alpha3" => "TTO", "phoneCode" => ["1-868"]],
        ["name" => "Tunisia", "numeric" => "788", "alpha2" => "TN", "alpha3" => "TUN", "phoneCode" => ["216"]],
        ["name" => "Turkey", "numeric" => "792", "alpha2" => "TR", "alpha3" => "TUR", "phoneCode" => ["90"]],
        ["name" => "Turkmenistan", "numeric" => "795", "alpha2" => "TM", "alpha3" => "TKM", "phoneCode" => ["993"]],
        ["name" => "Turks and Caicos Islands", "numeric" => "796", "alpha2" => "TC", "alpha3" => "TCA", "phoneCode" => ["1-649"]],
        ["name" => "Tuvalu", "numeric" => "798", "alpha2" => "TV", "alpha3" => "TUV", "phoneCode" => ["688"]],
        ["name" => "Uganda", "numeric" => "800", "alpha2" => "UG", "alpha3" => "UGA", "phoneCode" => ["256"]],
        ["name" => "Ukraine", "numeric" => "804", "alpha2" => "UA", "alpha3" => "UKR", "phoneCode" => ["380"]],
        ["name" => "United Arab Emirates", "numeric" => "784", "alpha2" => "AE", "alpha3" => "ARE", "phoneCode" => ["971"]],
        ["name" => "United Kingdom of Great Britain and Northern Ireland", "numeric" => "826", "alpha2" => "GB", "alpha3" => "GBR", "phoneCode" => ["44"]],
        ["name" => "United States of America", "numeric" => "840", "alpha2" => "US", "alpha3" => "USA", "phoneCode" => ["1"]],
        ["name" => "United States Minor Outlying Islands", "numeric" => "581", "alpha2" => "UM", "alpha3" => "UMI", "phoneCode" => ["1"]],
        ["name" => "Uruguay", "numeric" => "858", "alpha2" => "UY", "alpha3" => "URY", "phoneCode" => ["598"]],
        ["name" => "Uzbekistan", "numeric" => "860", "alpha2" => "UZ", "alpha3" => "UZB", "phoneCode" => ["998"]],
        ["name" => "Vanuatu", "numeric" => "548", "alpha2" => "VU", "alpha3" => "VUT", "phoneCode" => ["678"]],
        ["name" => "Venezuela (Bolivarian Republic of)", "numeric" => "862", "alpha2" => "VE", "alpha3" => "VEN", "phoneCode" => ["58"]],
        ["name" => "Vietnam", "numeric" => "704", "alpha2" => "VN", "alpha3" => "VNM", "phoneCode" => ["84"]],
        ["name" => "Virgin Islands (British)", "numeric" => "092", "alpha2" => "VG", "alpha3" => "VGB", "phoneCode" => ["1-284"]],
        ["name" => "Virgin Islands (U.S.)", "numeric" => "850", "alpha2" => "VI", "alpha3" => "VIR", "phoneCode" => ["1-340"]],
        ["name" => "Wallis and Futuna", "numeric" => "876", "alpha2" => "WF", "alpha3" => "WLF", "phoneCode" => ["681"]],
        ["name" => "Western Sahara", "numeric" => "732", "alpha2" => "EH", "alpha3" => "ESH", "phoneCode" => ["212"]],
        ["name" => "Yemen", "numeric" => "887", "alpha2" => "YE", "alpha3" => "YEM", "phoneCode" => ["967"]],
        ["name" => "Zambia", "numeric" => "894", "alpha2" => "ZM", "alpha3" => "ZMB", "phoneCode" => ["260"]],
        ["name" => "Zimbabwe", "numeric" => "716", "alpha2" => "ZW", "alpha3" => "ZWE", "phoneCode" => ["263"]]
    ];
}