<?php

namespace GlobalPayments\Api\Entities\Enums;

use GlobalPayments\Api\Entities\Enum;

class OperatingEnvironment extends Enum
{
    const NO_TERMINAL                           = 'NO_TERMINAL';
    const ON_MERCHANT_PREMISES_ATTENDED         = 'ON_MERCHANT_PREMISES_ATTENDED';
    const ON_MERCHANT_PREMISES_UNATTENDED       = 'ON_MERCHANT_PREMISES_UNATTENDED';
    const OFF_MERCHANT_PREMISES_ATTENDED        = 'OFF_MERCHANT_PREMISES_ATTENDED';
    const OFF_MERCHANT_PREMISES_UNATTENDED      = 'OFF_MERCHANT_PREMISES_UNATTENDED';
    const ON_CUSTOMER_PREMISES_UNATTENDED       = 'ON_CUSTOMER_PREMISES_UNATTENDED';
    const OFF_MERCHANT_PREMISES_MPOS            = 'OFF_MERCHANT_PREMISES_MPOS';
    const ON_MERCHANT_PREMISES_MPOS             = 'ON_MERCHANT_PREMISES_MPOS';
    const OFF_MERCHANT_PREMISES_CUSTOMER_POS    = 'OFF_MERCHANT_PREMISES_CUSTOMER_POS';
    const ON_MERCHANT_PREMISES_CUSTOMER_POS     = 'ON_MERCHANT_PREMISES_CUSTOMER_POS';
    const OFF_CUSTOMER_PREMISES_UNATTENDED      = 'OFF_CUSTOMER_PREMISES_UNATTENDED';
    const UNKNOWN                               = 'UNKNOWN';
    const ELECTRONIC_DELIVERY_AMEX              = 'ELECTRONIC_DELIVERY_AMEX';
    const PHYSICAL_DELIVERY_AMEX                = 'PHYSICAL_DELIVERY_AMEX';
}
