<?php
namespace GlobalPayments\Api\Entities\Reporting;

use GlobalPayments\Api\Entities\Enum;

class SearchCriteria extends Enum
{
    const ACCOUNT_NUMBER_LAST_FOUR = 'ACCOUNTNUMBERLASTFOUR';
    const ALT_PAYMENT_STATUS = 'ALTPAYMENTSTATUS';
    const AUTH_CODE = 'AUTHCODE';
    const BANK_ROUTING_NUMBER = 'BANKROUTINGNUMBER';
    const BATCH_ID = 'BATCHID';
    const BATCH_SEQUENCE_NUMBER = 'BATCHSEQUENCENUMBER';
    const BUYER_EMAIL_ADDRESS = 'BUYEREMAILADDRESS';
    const CARD_HOLDER_FIRST_NAME = 'CARDHOLDERFIRSTNAME';
    const CARD_HOLDER_LAST_NAME = 'CARDHOLDERLASTNAME';
    const CARD_HOLDER_PO_NUMBER = 'CARDHOLDERPONUMBER';
    const CARD_NUMBER_FIRST_SIX = 'CARDNUMBERFIRSTSIX';
    const CARD_NUMBER_LAST_FOUR = 'CARDNUMBERLASTFOUR';
    const CHECK_FIRST_NAME = 'CHECKFIRSTNAME';
    const CHECK_LAST_NAME = 'CHECKLASTNAME';
    const CHECK_NAME = 'CHECKNAME';
    const CHECK_NUMBER = 'CHECKNUMBER';
    const CLERK_ID = 'CLERKID';
    const CLIENT_TRANSACTION_ID = 'CLIENTTRANSACTIONID';
    const CUSTOMER_ID = 'CUSTOMERID';
    const DISPLAY_NAME = 'DISPLAYNAME';
    const END_DATE = 'ENDDATE';
    const GIFT_CURRENCY = 'GIFTCURRENCY';
    const GIFT_MASKED_ALIAS = 'GIFTMASKEDALIAS';
    const FULLY_CAPTURED = 'FULLYCAPTURED';
    const INVOICE_NUMBER = 'INVOICENUMBER';
    const ISSUER_RESULT = 'ISSUERRESULT';
    const ISSUER_TRANSACTION_ID = 'ISSUERTRANSACTIONID';
    const ONE_TIME = 'ONETIME';
    const PAYMENT_METHOD_KEY = 'PAYMENTMETHODKEY';
    const REFERENCE_NUMBER = 'REFERENCENUMBER';
    const SETTLEMENT_AMOUNT = 'SETTLEMENTAMOUNT';
    const SCHEDULE_ID = 'SCHEDULEID';
    const SITE_TRACE = 'SITETRACE';
    const START_DATE = 'STARTDATE';
    const UNIQUE_DEVICE_ID = 'UNIQUEDEVICEID';
    const USER_NAME = 'USERNAME';
}
